

CREATE TABLE OWNER (
    OwnerID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    ContactInfo VARCHAR(255) NOT NULL
);

CREATE TABLE MANAGER (
    ManagerID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    ContactInfo VARCHAR(255) NOT NULL,
    Department VARCHAR(100)
);

CREATE TABLE ARTIST (
    ArtistID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    ContactInfo VARCHAR(255) NOT NULL,
    AvailabilityStatus VARCHAR(50),
    Gender CHAR(1) CHECK (Gender IN ('M', 'F', 'O')),
    DateOfBirth DATE NOT NULL
);

CREATE TABLE CONTRACTED_ARTIST (
    ArtistID INT PRIMARY KEY,
    ContractID INT NOT NULL,
    Salary DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID)
);

CREATE TABLE PROSPECTIVE_ARTIST (
    ArtistID INT PRIMARY KEY,
    ApplicationStatus VARCHAR(50),
    PortfolioLink VARCHAR(255),
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID)
);

CREATE TABLE MARKETING (
    MarketingID INT PRIMARY KEY AUTO_INCREMENT,
    ArtistID INT NOT NULL,
    Promotion TEXT,
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID)
);

CREATE TABLE TRAVEL (
    TravelID INT PRIMARY KEY AUTO_INCREMENT,
    ArtistID INT NOT NULL,
    TravelCost DECIMAL(10,2) NOT NULL,
    Destination VARCHAR(255) NOT NULL,
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID)
);

CREATE TABLE AVAILABILITY (
    AvailabilityID INT PRIMARY KEY AUTO_INCREMENT,
    ArtistID INT NOT NULL,
    Date DATE NOT NULL,
    Status VARCHAR(50),
    Location VARCHAR(255),
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID)
);

CREATE TABLE EVENT (
    EventID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Date DATE NOT NULL,
    VenueID INT NOT NULL,
    OrganizerID INT NOT NULL
);

CREATE TABLE SCHEDULE (
    ScheduleID INT PRIMARY KEY AUTO_INCREMENT,
    ArtistID INT NOT NULL,
    EventID INT NOT NULL,
    DateTime DATETIME NOT NULL,
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID),
    FOREIGN KEY (EventID) REFERENCES EVENT(EventID)
);

CREATE TABLE FINANCIAL_TRANSACTION (
    TransactionID INT PRIMARY KEY AUTO_INCREMENT,
    PaymentID INT NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    PaymentMethod VARCHAR(50),
    Date DATE NOT NULL
);

CREATE TABLE PAYMENT (
    PaymentID INT PRIMARY KEY AUTO_INCREMENT,
    ArtistID INT NOT NULL,
    EventID INT NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    PaymentStatus VARCHAR(50),
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID),
    FOREIGN KEY (EventID) REFERENCES EVENT(EventID)
);

CREATE TABLE PERFORMANCE (
    PerformanceID INT PRIMARY KEY AUTO_INCREMENT,
    ArtistID INT NOT NULL,
    Source VARCHAR(255),
    Summary TEXT,
    ReviewRatings DECIMAL(3,2),
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID)
);

CREATE TABLE VENUE (
    VenueID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Capacity INT NOT NULL
);

CREATE TABLE PERFORMANCE_REPORT (
    ReportID INT PRIMARY KEY AUTO_INCREMENT,
    EventID INT NOT NULL,
    ArtistID INT NOT NULL,
    Rating DECIMAL(3,2),
    Comments TEXT,
    FOREIGN KEY (EventID) REFERENCES EVENT(EventID),
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID)
);

CREATE TABLE EVENT_ORGANIZER (
    OrganizerID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    ContactInfo VARCHAR(255) NOT NULL
);

CREATE TABLE CONTRACT (
    ContractID INT PRIMARY KEY AUTO_INCREMENT,
    ArtistID INT NOT NULL,
    ManagerID INT NOT NULL,
    EventID INT NOT NULL,
    Terms TEXT,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID),
    FOREIGN KEY (ManagerID) REFERENCES MANAGER(ManagerID),
    FOREIGN KEY (EventID) REFERENCES EVENT(EventID)
);

CREATE TABLE FINANCE (
    TransactionID INT PRIMARY KEY AUTO_INCREMENT,
    ContractID INT NOT NULL,
    Earning DECIMAL(10,2),
    TaxDeduction DECIMAL(10,2),
    FinalPayment DECIMAL(10,2),
    FOREIGN KEY (ContractID) REFERENCES CONTRACT(ContractID)
);

CREATE TABLE PERFORMANCE_REFERENCES (
    ReferenceID INT PRIMARY KEY AUTO_INCREMENT,
    PerformanceID INT NOT NULL,
    FOREIGN KEY (PerformanceID) REFERENCES PERFORMANCE(PerformanceID)
);
